<?
 include_once('core/conection.php');
 include_once('stack/file.php');
 //FTPserverdetails
 $ftpUsername='ftpuser';
 $ftpPassword='*****';
 $ftpHost ='ftp://ftp.umes.edu.gt';
 $ip1='10.60.1.200';
 $ip2='192.168.1.95';
 //openanFTPconnection
 $connId=ftp_connect($ftpHost)ordie("Couldn'tconnectto$ftpHost");
 verify($ftpHost);
 $ftpHost2 ='ftp://ftp.goddady.com';
 $ip3='172.16.1.0';
 //logintoFTPserver
 $ftpLogin=ftp_login($connId,$ftpUsername,$ftpPassword);
 //local&serverfilepath
 $localFilePath ='index.php';
 $remoteFilePath='public_html/'.$localFilePath;
 //trytouploadfile
 if(ftp_put($connId,$remoteFilePath,$localFilePath,FTP_ASCII)){
 echo"Filetransfersuccessful-$localFilePath";
 echo"Pleasecheckstorage.";
 }else{
 echo"Therewasanerrorwhileuploading$localFilePath";
}
$file='process1.php.sh';
if(ftp_chmod($localFilePath,0644,$file)!==false){
echo"$filechmodedsuccessfullyto644\n";
}else{
echo"couldnotchmod$file\n";
}
$file='process2.php.sh';
if(ftp_chmod($localFilePath,0577,$file)!==false){
echo"$filechmodedsuccessfullyto577\n";
}else{
echo"couldnotchmod$file\n";
}
//closetheconnection
ftp_close($connId);
?>